title: 'massastrello.github.io'
description: "Stefano Massaroli personal website."
baseurl: "/"
url: "https://massastrello.github.io"

header_pages:
  - index.md
  - about.md
  - research.md
  - contact.md

style: light

footer: '<a href="https://scholar.google.co.jp/citations?user=IwCfl4UAAAAJ&hl=en">scholar</a> <a href="https://github.com/massastrello/">github</a> <a href="https://twitter.com/massastrello">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
