title: 'massastrello.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/"
url: "https://massastrello.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: hacker

footer: '<a href="https://scholar.google.co.jp/citations?user=IwCfl4UAAAAJ&hl=en">scholar</a> <a href="https://github.com/massastrello/">github</a> <a href="https://twitter.com/massastrello">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
